# help from https://binary-studio.com/blog/2021/12/21/lint-your-project-with-github-actions/

name: Linter

on: 
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

env:
  NODE_VERSION: 20

jobs: # list of things to do
  linting:
    name: ESLint
    runs-on: ubuntu-latest # on which machine to run
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npx eslint frontend --max-warnings 0
